# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
tens = torch.rand(7,7)
tens, tens.shape

(tensor([[0.2157, 0.0636, 0.4741, 0.5750, 0.6870, 0.0089, 0.5137],
         [0.3657, 0.1162, 0.7595, 0.0017, 0.5269, 0.9579, 0.3506],
         [0.5884, 0.6175, 0.3181, 0.4870, 0.7251, 0.6519, 0.8116],
         [0.8512, 0.2585, 0.7498, 0.7339, 0.5064, 0.4091, 0.1979],
         [0.3117, 0.6710, 0.8131, 0.4720, 0.9634, 0.9515, 0.2213],
         [0.7824, 0.0709, 0.3993, 0.6220, 0.7847, 0.0986, 0.8096],
         [0.5209, 0.5998, 0.8357, 0.7712, 0.5712, 0.2008, 0.2378]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
tens2 = torch.rand(1, 7)
tens2 = tens2.T
tens @ tens2
# Perform matrix multiplication


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
random_seed = 0

# Create two random tensors
torch.manual_seed(random_seed)
rand_tens1 = torch.rand(7, 7)
torch.manual_seed(random_seed)
rand_tens2 = torch.rand(1, 7)
rand_tens2 = rand_tens2.T
# Matrix multiply tensors
rand_tens1 @ rand_tens2

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
t1 = torch.rand(2,3)
t1_gpu = t1.to(device='cuda')
torch.manual_seed(1234)
t2 = torch.rand(2,3)
t2_gpu = t2.to(device='cuda')
print(t1_gpu, t1_gpu.device)
print(t2_gpu, t2_gpu.device)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
end_tens = torch.tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]])


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
mx = end_tens.max()
# Find min
mn = end_tens.min()

tensor(0.3647)

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
arg_mx = end_tens.argmax()

# Find arg min
arg_mn = end_tens.argmin()
print(arg_mx, arg_mn)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
seed = 7

# Create random tensor
torch.manual_seed(seed)
ten = torch.rand(1, 1, 1, 10)
# Remove single dimensions
ten = ten.reshape(10)
ten

# Print out tensors and their shapes


tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])