In [ ]:
import torch

In [ ]:
scalar = torch.tensor([[1,2,3], [2, 7, 5]])
print(scalar.ndim)
print(scalar.shape)

2
torch.Size([2, 3])


In [ ]:
rand_tens = torch.rand(size=(2,3,4))
rand_tens

In [ ]:
rand_tens.device

device(type='cpu')

In [ ]:
tens1 = torch.tensor([[1, 2],
         [2, 4],
         [3, 3]])
tens2 = torch.tensor([[1, 5],
         [2, 6],
         [2, 10]])
tens2 = tens2.T
tens1 @ tens2

In [ ]:
x = torch.arange(0, 100, 10)
x.max()
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
tens = torch.arange(1, 10)
print(tens, tens.shape)
tens_reshaped = tens.reshape(1, 9)
print(tens_reshaped, tens_reshaped.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])


In [ ]:
tens2 = torch.arange(10, 19)
stacked = torch.stack([tens, tens, tens2], dim=1)
print(stacked)

tensor([[ 1,  1, 10],
        [ 2,  2, 11],
        [ 3,  3, 12],
        [ 4,  4, 13],
        [ 5,  5, 14],
        [ 6,  6, 15],
        [ 7,  7, 16],
        [ 8,  8, 17],
        [ 9,  9, 18]])


In [ ]:
stacked[:, 2]

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
random_seed = 43
torch.manual_seed(random_seed)
x1 = torch.rand(3, 4)
torch.manual_seed(random_seed)
x2 = torch.rand(3, 4)
x1, x2

In [ ]:
torch.cuda.is_available()

False

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

In [ ]:
torch.cuda.device_count()

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu